### ISSUE TITLE
Steering Weight on EPS module

### ISSUE THREAD

**Issue by ezhik1** [packetpilot/bmw-f#112]
Hi there!

I scoured the interwebz for any cases of people successfully getting to the EPS module on an F30 and customizing steering assist torque.  I've not found anything terribly useful on the forums, so perhaps this is achievable through e-sys and a bit of digging. 

I'm led to believe that the weights are described somewhere, since the car applies variable weight to the EPS motor under these observed conditions:

- toggling `sport` | `comfort` at low speed creates a noticeable (albeit slight) difference in steering effort
- comparing steering effort at 20mph vs 80mph steering effort becomes progressively heavier

From those two findings, I'm certain there's a couple scalars, or a table of arbitrary weights that eventually correspond to final calculations that dictate motor torque on the EPS itself.

I've considered these three things:

1. Disconnect the EPS module and steer with no PS (worth trying, seems straightforward, probably not without CELs, and will likely be too heavy.)

2. Install a considerably large resistor to limit power to the electric motor
 -- seems to be impractical, as at least some documentation on EPS modules on other platforms seems to consume  10-1kW  ([page 16](https://www.scribd.com/document/387054264/06-Lateral-Dynamics-Y-Axis))
 --1kw resistor in the engine bay, while a fun practical idea, is not something I can *comfortably* live with day-to-day. 

3.  Change the gear ratio in the EPS box. seems the driving gear could be replaced with something smaller, reducing torque delivered to the final output, but I'd likely need to have one custom milled, and have to drop the rack, rebuild, etc. Not terribly fun. 

Being that the system itself is pretty darn clean and superior to the hydro racks, I'd like to solve this with software, because it's the offender. If we can change a set of consts to make steering weight heavier (and constant) across all the driving modes, and conditions, that'd be amazing!! Even bumping the current values by some arbitrary (heavier) amount would be more than enough! 

If you have thoughts, I'd love to chat about this stuff.  As luck would have it, I'm also in Mountain View.

**Comment by botho** [comment]
please, considering to chat about coding on dedicated forum.
Not the right place
