### ISSUE TITLE
Not Allowing Pull Request

### ISSUE THREAD

**Issue by taintfair** [packetpilot/bmw-f#80]
I fixed the formatting and everything looks good on my fork, but for some reason it is saying the master is up to date.  On the master it still has the old one.  Can you pull from my fork without a request?  Is there another way to get the master up to date?

**Comment by botho** [comment]
You file is 2 days ago into your repository ?
Upload your changes into your fork and then create a pull request

**Comment by taintfair** [comment]
That’s my confusion I’ve uploaded the changes into my form.

**Comment by botho** [comment]
don't forget to commit your work. Again, into your repository, your file is 2 days old

**Comment by taintfair** [comment]
Not sure what happened.  I deleted and uploaded again.  Seemed to work.
