### ISSUE TITLE
Labeling NGHB 

### ISSUE THREAD

**Issue by Almaretto** [packetpilot/bmw-f#86]
It is helpful to include Chassis in description name because F15 and F06 can also have these FLE's.

**Comment by botho** [comment]
Hi Almaretto,
Could you be more specific please ?
Wihich XML are you talking about exactly

**Comment by Almaretto** [comment]
https://github.com/packetpilot/bmw-f/blob/master/cheats/Kip_M3.xml

**Comment by botho** [comment]
can't understand what is your issue. Could you please patch the file and pull request for merge ?
Regards

**Comment by Almaretto** [comment]
Chassis are listed but not in description. 

 <cafd id="000024C3" name="FLE 43/44" author="Kip_M3" series="F080,F082">
        <code description="No Amber Enable GFHB/antidazzle high beams - Euro settings">

If someone does not use chassis filter, then could apply incorrect codes to car.

**Comment by botho** [comment]
Done
